### ISSUE TITLE
rct_atst_weights

### ISSUE THREAD

**Issue by qingkezyy** [Audio-WestlakeU/ATST-RCT#1]
Hi, I'm not sure if rct_atst_weights uses the pre-trained weights of RCT or the pre-trained model weights provided in ATST.

**Comment by SaoYear** [comment]
Hi, thanks for your interest!

rct_atst_weights shall stands for the pretrained ATST weights.

Both pretrained weights are used in this system. The CNN pretrained weights provide a marginal promotion on the performance. And the pretrained weights of the ATST play a more important role. 

You could of coure train the CNN part from scratch.

**Comment by qingkezyy** [comment]
Thanks for the reply, it was very helpful to me!

 So can I understand that the same thing is stored under the path of pretrained_ckpt_path and rct_atst_weights?

For example, in the fusion_rct.yaml file:
net:
  atst_mode: base  # small or base
  pretrained_ckpt_path:  "./pretraining/ATST/base/rct.ckpt"
  pretrained_crnn:   "./pretraining/CRNN/rct.ckpt"
  freeze_cnn: False
  audio_len: 10
  n_last_blocks: 2
  n_class: 10
  chunk_input: False
  unfreeze: 3
  rct_atst_weights:  "./pretraining/ATST/base/rct.ckpt"

**Comment by SaoYear** [comment]
Yeah, its the same thing. But in our submitted system, we used a ATST checkpoint finetuned for SED task.  

I just checked the logs but I think the finetuned checkpoint were deleted... But ideally, using vanilla ATST checkpoint also works (or maybe you can finetune one)

Sorry for the misleading points in the code : )

**Comment by qingkezyy** [comment]
Yes, I ran the results using vanilla ATST checkpoint, would it be better if I used ATST checkpoint finetuned for SED task?

**Comment by SaoYear** [comment]
Yes, it would be : )

**Comment by qingkezyy** [comment]
Thank you for your patient reply, I will close this issue.
